#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "toshkoevoets" --password-stdin;
docker push toshkoevoets/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID}
docker tag toshkoevoets/${DOCKER_IMAGE_NAME}:${TRAVIS_BUILD_ID} ${DOCKER_PUBLIC_USERNAME}/${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}
docker push toshkoevoets/${DOCKER_IMAGE_NAME}:${TRAVIS_TAG}
