#!/usr/bin/env bash

# shared settings NOT added to git
if [ -f ./setenv.shared ]; then
  source ./setenv.shared
fi

# private settings NOT added to git
if [ -f ./setenv.${USER} ]; then
  source ./setenv.${USER}
fi

# Make sure we have node and npm
if [ ! $(command -v nvm) ]; then
  curl -o- https://raw.githubusercontent.com/creationix/nvm/v0.38.0/install.sh | bash
fi

# setup correct node version
nvm install
nvm use